name: Auto Sync to Gitee
on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Push to Gitee
      run: |
        git remote add gitee https://meloncar:${{ secrets.GITEE_TOKEN }}@gitee.com/meloncar/Calculator.git
        git push -f gitee main
